# Generated by Django 3.1.13 on 2022-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='')),
                ('subject', models.CharField(blank=True, max_length=400, verbose_name='')),
                ('message', models.CharField(blank=True, max_length=1000, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects_images', verbose_name='Image')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
